[package]
name = "advent-of-rust-2024"
version = "0.1.0"
edition = "2021"
authors = ["James Youngman <james@youngman.org>"]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
clap = "4"
itertools = "0.13"

[lib]
name = "lib"
path = "src/lib/lib.rs"

[[bin]]
name = "day01"
